# ServiceAccount — идентификатор приложения внутри кластера.
# Principle of least privilege: pod имеет только те права что ему нужны.
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "payment-gateway.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "payment-gateway.labels" . | nindent 4 }}
  annotations:
    # Если используешь AWS IRSA (IAM Roles for Service Accounts):
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/payment-gateway
automountServiceAccountToken: false  # не монтируем токен если k8s API не нужен
{{- end }}
